export const drinks = [
  { name: 'Affogato', art: false },
  { name: 'Affogato', art: false },
  { name: 'V60 Filter', art: false },
  { name: 'Clever Filter', art: false },
  { name: 'Japanese Filter (v60)', art: false },
  { name: 'Japanese Filter (Clever)', art: false },
  { name: 'Tubruk susu', art: false },
  { name: 'Tubruk', art: false },
  { name: 'Kopi susu Amstir', art: false },
  { name: 'Mocha', art: true },
  { name: 'Mocha', art: true },
  { name: 'Iced Mocha', art: false },
  { name: 'Iced Mocha', art: false },
  { name: 'Iced Americano', art: false },
  { name: 'Hot Americano', art: false },
  { name: 'Picollo', art: true },
  { name: 'Es Kopi Susu', art: false },
  { name: 'Cortado', art: true },
  { name: 'Cafe Latte', art: true },
  { name: 'Espresso', art: false },
  { name: 'Ristretto', art: false },
  { name: 'Capuccino', art: true },
  { name: 'Flat White', art: true },
  { name: 'Magic', art: true },
  { name: 'Vietnam Drip', art: false },
  { name: 'Iced Vietnam Drip', art: false },
];
