export const drinks = [
  { name: 'Affogato', art: false },
  { name: 'Filter', art: false },
  { name: 'Japanese Filter', art: false },
  { name: 'Tubruk', art: false },
  { name: 'Mocha', art: true },
  { name: 'Iced Americano', art: false },
  { name: 'Picollo', art: true },
  { name: 'Es Kopi Susu Brown Sugar', art: false },
  { name: 'Goth Latte', art: true },
  { name: 'Cortado (White Ceramic)', art: true },
  { name: 'Cafe Latte (Cream Ceramic)', art: true },
  { name: 'Large Cafe Latte (Ikea)', art: true },
  { name: 'Ristretto', art: false },
  { name: 'Doppio', art: false },
  { name: 'Lungo', art: false },
  { name: 'Hot Capuccino (glass 170ml)', art: true },
  { name: 'Flat White (Black Ceramic)', art: true },
];
